version: '3'
services:
  solr:
    image: solr:8.7.0
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    healthcheck:
      test: >-
        curl -s -A 'healthcheck'  http://localhost:8983/solr/gettingstarted/admin/ping?wt=json \
        | grep -q '"status":"OK"'
volumes:
  data:
